# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: true
dist: trusty 

env:
    global:
        - MAKEFLAGS="-j 2"

  
matrix:
  include:
    - r: oldrel
    - r: release
      env: R_RELEASE=true  
    - r: devel
      env: R_DEVEL=true

    
github_packages:
    rethomics/behavr

script:
    - R CMD build .
    - R CMD check *tar.gz
    - if [[ "${R_RELEASE}" ]]; then sh .publish_doc.sh; fi

after_success:
    - if [[ "${R_RELEASE}" ]]; then R -e 'covr::codecov()'; fi
#- if [[ "${R_DEVEL}" ]]; then cat /home/travis/build/rethomics/behavr/behavr.Rcheck/00install.out; fi

notifications:
    email:
        on_success: change
        on_failure: change
